Formal verification of ECDH with P-384
awslabs/aws-lc-verification pull request #130
Opened 2023-12-07 13:47 UTC by apetcher-amazon

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Proof of correctness of the base point multiplication operation for P-384 and documentation describing the formal verification of ECDH with P-384. There are some significant caveats that should be adequately described in the documentation---the pre-computed table of multiples of the base point is assumed to be correct, and the point conversion functions are assumed to be correct.

2023-12-14 01:47 UTC, pennyannn requested changes

2023-12-14 01:47 UTC, pennyannn commented on Coq/EC/GroupMulWNAF.v
> +  Fixpoint groupMul_signedWindows_exp (ws : list SignedWindow) n : GroupElem :=
Add a comment for what `groupMul_signedWindows_exp` does.

2023-12-14 01:47 UTC, pennyannn commented on Coq/EC/GeneratorMul.v
> +  Definition groupedMul_precomp d ws :=
Add a comment describing what this function represents.

2023-12-14 01:47 UTC, pennyannn commented on Coq/EC/GeneratorMul.v
> +  Fixpoint basePreCompTable m x n :=
Add a comment for this function.

2023-12-14 14:12 UTC, apetcher-amazon commented on README.md
> +| SAWCore_Coq | Certain facts are admitted in Coq code provided by the saw-core-coq library. |
This is true, but it's not obvious why this should be listed as a caveat. We trust that SAW is correct, and the translation from Cryptol to Coq (through SAWCore) is just one aspect of this trust. E.g. we also trust SAW to correctly produce proof obligations to send to the SMT solvers. Though let me know if I'm missing some motivation for listing this as a caveat. 

This caveat about facts admitted in Coq is listed because it explains why these axioms are admitted, and it makes it clear that our trust in SAW is spilling over into Coq, and it can affect the correctness of the Coq proofs that should otherwise be independent of SAW.

2023-12-14 14:17 UTC, apetcher-amazon commented on README.md
> +| [ECDSA](SPEC.md#ECDSA) | with <nobr>P-384</nobr>, <nobr>SHA-384</nobr> | EVP_DigestSignInit, EVP_DigestVerifyInit, EVP_DigestSignUpdate, EVP_DigestVerifyUpdate, EVP_DigestSignFinal, EVP_DigestVerif
`EC_Ops_Correct` is intended to be a much broader caveat that covers all the others. For ECDSA, we assume the correctness of all operations on points. So that implies that we assume the correctness of point conversion operations, there is no need to worry about axioms in Coq because this Coq proof isn't used, etc. Let me know if you have suggestions on how to improve the wording of the caveats to make this more clear.

2023-12-14 14:26 UTC, apetcher-amazon commented on Coq/EC/WindowedMulMachine.v
> +Section MachineEval.
Done.

2023-12-14 14:30 UTC, apetcher-amazon commented on Coq/EC/WindowedMulMachine.v
> +  Theorem permuteAndDouble_equiv : forall ws d perm doubles ps,
Done.

2023-12-14 14:57 UTC, apetcher-amazon commented on Coq/EC/WindowedMulMachine.v
> +(* Insert a double at the head of the list and adjust exponents on remaining items *)
Done

2023-12-14 15:12 UTC, apetcher-amazon commented on Coq/EC/GroupMulWNAF.v
> +  Fixpoint groupMul_signedWindows_exp (ws : list SignedWindow) n : GroupElem :=
Done. I also moved this definition into WindowedMulMachine, since it is only used in proofs in that file.

2023-12-14 15:23 UTC, apetcher-amazon commented on Coq/EC/GeneratorMul.v
> +  Definition groupedMul_precomp d ws :=
Done.

2023-12-14 15:26 UTC, apetcher-amazon commented on Coq/EC/GeneratorMul.v
> +  Fixpoint basePreCompTable m x n :=
I removed it. It isn't needed for this proof.

2023-12-14 18:21 UTC, khieta approved these changes
Overall, looks good. Left a few small comments.

One general comment: it would make the proofs cleaner to move utility definitions and proofs (e.g., about `combineOpt`, `nth`, `nth_error`, `Forall2`) into a separate Util.v file.

2023-12-14 18:21 UTC, khieta commented on README.md
>  | --------------| ------------|
This is a neat way to document your assumptions. It would be even neater if each description included the `Hypothesis` (or other relevant piece of code) that it corresponds to. For example, I assume `EC_Constants_Correct` corresponds to `base_precomp_table_correct`?

2023-12-14 18:47 UTC, pennyannn commented on README.md
> +| SAWCore_Coq | Certain facts are admitted in Coq code provided by the saw-core-coq library. |
That makes sense. Thanks for the clarification.

2023-12-14 21:03 UTC, apetcher-amazon commented on README.md
> +| [ECDSA](SPEC.md#ECDSA) | with <nobr>P-384</nobr>, <nobr>SHA-384</nobr> | EVP_DigestSignInit, EVP_DigestVerifyInit, EVP_DigestSignUpdate, EVP_DigestVerifyUpdate, EVP_DigestSignFinal, EVP_DigestVerif
I changed things a bit in an attempt to clarify. I removed `EC_Ops_Correct` and replaced it with a new caveat `EC_Pub_Mul_Correct` that describes the assumption that you would need to make about the public point multiplication function in order to conclude that the ECDSA implementation is correct. Then I added this caveat and the other caveats mentioned above to ECDSA. This change makes the documentation more precise, and hopefully more clear. Let me know what you think.  

I want to keep the caveats separate, because they are mostly independent, and I'm hoping to remove some of them with follow-on work in the near future. I prefer to have separate caveats now rather than trying to untangle things later.

2023-12-14 21:04 UTC, apetcher-amazon commented on Coq/EC/GeneratorMul.v
> +End ComputeBaseTable.
Nope. Removed.

2023-12-14 21:08 UTC, apetcher-amazon commented on Coq/EC/GeneratorMul.v
> +Section GeneratorMulWNAF.
Fixed.

2023-12-14 23:54 UTC, pennyannn commented on README.md
> +| [ECDSA](SPEC.md#ECDSA) | with <nobr>P-384</nobr>, <nobr>SHA-384</nobr> | EVP_DigestSignInit, EVP_DigestVerifyInit, EVP_DigestSignUpdate, EVP_DigestVerifyUpdate, EVP_DigestSignFinal, EVP_DigestVerif
Sounds good to me. This approach is more consistent with ECDH's description.

2023-12-15 19:56 UTC, apetcher-amazon commented on Coq/EC/GeneratorMul.v
> +    groupAdd a b == groupAdd b a.
I factored this out into a `Class` in new file CommutativeGroup.v. This is very similar to an existing definition in Fiat Crypto, but I prefer that the abstract algebra parts of this proof are independent of Fiat Crypto.

2023-12-15 20:08 UTC, apetcher-amazon commented on Coq/EC/WindowedMulMachine.v
> +  if (ge_dec v y) then (if (divides x (v - y)) then true else false) else false.
This function is used as part of a large computation, so I think it needs to be `bool` so I can destruct it in an `if` in that computation. E.g. see how it is used in the `lsMultiples` function.

2023-12-15 20:08 UTC, apetcher-amazon commented on Coq/EC/WindowedMulMachine.v
> +  Hypothesis groupAdd_proper : Proper (equiv ==> equiv ==> equiv) groupAdd.
Fixed.

2023-12-15 20:08 UTC, apetcher-amazon commented on Coq/EC/ECEqProof.v
> -  Hypothesis felem_sqr_spec : forall (x : F), Fsquare x = Fmul x x.
Done.

2023-12-15 20:15 UTC, apetcher-amazon commented on README.md
>  | --------------| ------------|
Right. Also, `Fone_eq` contributes to this caveat, and so do some other hypotheses that I have removed in my next push under this PR (e.g. the assumption that all points in the table are on the curve, which is implied by `base_precomp_table_correct`). 

Unfortunately, I don't think there is a consistent way to link caveats to proofs. In some cases, the caveat is caused by the complete absence of something (e.g. there is no tooling that is aware of the Arm ABI and ensures parameters are passed correctly between C and Arm assembly code). Though I agree that having traceability between these caveats and proof artifacts (or lack thereof) would be valuable. We will have to give this more thought.

2023-12-16 18:39 UTC, pennyannn commented
Submodule src is out of sync with master branch, causing CI failure.

2023-12-18 19:02 UTC, pennyannn approved these changes

2023-12-19 19:03 UTC, merged