Add unbounded AES-GCM verification, isolate newer SAW from other proofs
awslabs/aws-lc-verification pull request #144
Opened 2024-04-24 18:28 UTC by RyanGlScott

This proves unbounded AES-GCM functions, building on top of the cryptol-specs work in https://github.com/GaloisInc/cryptol-specs/pull/72 and the saw-script work in https://github.com/GaloisInc/saw-script/pull/2037. This supersedes previous efforts in https://github.com/awslabs/aws-lc-verification/pull/80, https://github.com/awslabs/aws-lc-verification/pull/139, and #143.

This requires a newer version of SAW to work than what aws-lc-verification's CI currently uses, so I isolated these proofs into their own SAW scripts, Cryptol specs, shell scripts, Docker image, and CI action. Moreover, some of the AES-GCM proofs use Z3's Constrained Horn Clause (CHC) feature, which is buggy on Z3-4.8.8. aws-lc-verification's other CI jobs are currently using Z3-4.8.8, so I specifically chose a newer version (Z3-4.8.14) for the new, AES-GCM–specific CI job.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-24 18:38 UTC, RyanGlScott commented
Ah, I mistakenly introduced some changes to `SAW/proof/common/helpers.saw` which require a newer version of SAW, but weren't properly isolated to only affect AES-GCM. I'll push a fix momentarily.

2024-04-24 20:02 UTC, RyanGlScott commented
At long last, the CI finally passes! Ready for review, @apetcher-amazon and @pennyannn.

2024-04-25 13:58 UTC, apetcher-amazon commented
I have a few high-level comments before I examine the details.

1. A big thing that is missing is an indication of how well the proof can be parallelized. Unless I'm missing something, the current scripts appear to only check a single pair of `mres` and `res_mres` values because `AES-GCM-check-entrypoint.go` just falls through to `AES_GCM.saw`. You should be able to modify the Go scripts to execute `AES_GCM.saw` in parallel with multiple parameter values. Can you try this so we can get some indication of how much RAM is needed and how well we can parallelize the proof? You don't need to run the SAW script on all parameter values---just show how many parameter values we can check in parallel. The runner that we are using for the CI has 64 GB of RAM. 
2. In SPEC.md, you should describe the spec of the top-level functions like `EVP_EncryptUpdate` and `EVP_EncryptFinal`. There is no need to include specs for internal functions.
3. The Cryptol spec for AES-GCM is very hard to follow. Can you organize/simplify it a bit and/or add some comments. It needs to be easy for someone to examine it and agree that it describes (some implementation-specific variant of) AES-GCM.
4. In general, the code could be improved with more comments and some slight tweaks to organization. Please look over the code and make sure that magic numbers are explained and defined using constants(e.g. why length is a 28-bit integer), variable names are clear or described using documentation (e.g. meaning of `mres` and `res_mres` are not clear from the name), etc. Also, move large proof scripts that do not need to be inspected out of top-level files like `AES-GCM.saw` so it is easier to see what is proved.

2024-04-25 20:26 UTC, RyanGlScott commented
> 1. A big thing that is missing is an indication of how well the proof can be parallelized.

Yes, a fair point. I can experiment locally to see how well we can parallelize it, although my local machine only has 32 GB of RAM.

> 2. In SPEC.md, you should describe the spec of the top-level functions like `EVP_EncryptUpdate` and `EVP_EncryptFinal`. There is no need to include specs for internal functions.

Ah, good to know. I'll do that.

> 3. The Cryptol spec for AES-GCM is very hard to follow. Can you organize/simplify it a bit and/or add some comments. It needs to be easy for someone to examine it and agree that it describes (some implementation-specific variant of) AES-GCM.

Yes, quite so. One of the challenges here is that much of the Cryptol code checked in here is not meant to reflect the official NIST AES-GCM specification so much as it is an aid for SAW to help identify the loop structure of the C code itself, so it is written in a much more "low-level" style than what you'd find in the NIST spec. The Cryptol code that is closer to the NIST spec is found in https://github.com/GaloisInc/cryptol-specs/pull/72 (in `AES_256_GCM.cry`).

That being said, the comments could definitely explain all this better. I'll do that and add some more commentary where I can.

> 4. In general, the code could be improved with more comments and some slight tweaks to organization. Please look over the code and make sure that magic numbers are explained and defined using constants(e.g. why length is a 28-bit integer), variable names are clear or described using documentation (e.g. meaning of `mres` and `res_mres` are not clear from the name), etc. Also, move large proof scripts that do not need to be inspected out of top-level files like `AES-GCM.saw` so it is easier to see what is proved.

Sure, will do.

2024-04-25 22:39 UTC, pennyannn commented
I want to confirm if my understanding is correct. In this proof, the bulk processing functions `aesni_gcm_encrypt` and `aesni_gcm_decrypt` are verified with arbitrary input length, therefore they are unbounded proofs. 

For all other functions, they are all bounded proofs serving some purpose, and this includes proofs for the top-level EVP functions as well. For example, `aes_hw_ctr32_encrypt_blocks` is only verified with number of blocks smaller than `MIN_BULK_BLOCKS = 18`. This is because this function is only used when there aren't enough message blocks to do one loop iteration of bulk processing. Likewise for GHASH functions like `gcm_ghash_avx`.

For top-level EVP function, I believe only one set of verification parameter is chosen for the proof, so it is also a bounded proof. The override matching to bulk functions `aesni_gcm_encrypt` and `aesni_gcm_decrypt` will automatically figure out what the message block length is. 

Is my understanding correct?

If so, could you add some comments to the proof command for the top-level EVP functions (the various `llvm_verify` for `EVP_EncryptUpdate` and `EVP_DecryptUpdate`) explaining the meaning of the input numbers. What do they refer to and why we are choosing this set of parameter?

2024-04-26 06:29 UTC, pennyannn commented on Dockerfile.saw_x86_aes_gcm
> +FROM ubuntu:20.04
I'm a bit confused. I thought we need ubuntu:22.04 to run the new SAW but this dockerfile uses ubuntu:20.04, and the CI still passes?

2024-05-01 20:05 UTC, pennyannn commented
Wow, this is so cool! All workflow pass and apparently the proofs now run faster even though we are checking more combinations of parameters! I wonder if it is because you removed the bounded proofs. I will start reviewing. Thank you so much for the help, @RyanGlScott !

2024-05-02 06:19 UTC, pennyannn requested changes
I have reviewed the workflow, shell scripts and most of the SAW files (excluding goal-rewrites files). I will send another review for the Cryptol files.

2024-05-02 06:19 UTC, pennyannn commented on SAW/proof/AES/GHASH.saw
> +      goal_eval_unint ["pmult", "pmod", "gcm_polyval"];
I wonder what's going on here that we need to do `goal_eval_unint ["pmult", "pmod", "gcm_polyval"];` so many times.

2024-05-02 06:19 UTC, pennyannn commented on SPEC.md
> +| EVP_CipherInit_ex | <ul><li>The global variable `OPENSSL_ia32cap_P` exists and points to a value that [disables `AVX512[F|DQ|BW|VL]` instructions](https://www.openssl.org/docs/manmaster/man3/OPENSS
There seems to be some formatting issue with this table.

2024-05-02 12:54 UTC, apetcher-amazon commented on SPEC.md
> +| EVP_DecryptFinal_ex | <ul><li>The `ctx` field is initialized for AES-GCM using AES-256.</li><li>The `ctx` field's `cipher` parameter is a valid `EVP_CIPHER` such as the value returned by `EVP_aes_2
typo: "functio"

2024-05-02 12:54 UTC, apetcher-amazon commented on README.md
> +| [<nobr>AES-GCM</nobr>](SPEC.md#AES-GCM) | 256 | gcm_ghash_avx, aes_hw_ctr32_encrypt_blocks, aesni_gcm_encrypt, aesni_gcm_decrypt | SandyBridge+ | MemCorrect, NoInline | SAW |
Change these function names to the EVP functions listed in SPEC.md.

Also, add caveats for any assumptions/limitations/etc associated with this proof. Here are the ones that I could think of:
* AES/GCM is verified using an implementation-specific Cryptol spec describing an optimized form of AES/GCM. 
* Only verified for cases where whole blocks are encrypted/decrypted---i.e. length passed to EVP_{Encrypt/Decrypt}Update is a multiple of 16. (This is true because we are verifying the case where mres=0 and res_mres=0. We verify other cases, too, but they are not as easy to characterize. We can remove this caveat if we set up the CI to cover all cases). 
* Supplying additional data (AD) is not verified. In order to verify this case, we would need to develop SAW proofs for EVP_{Encrypt/Decrypt}Update where the output buffer pointer is null. 
* Only verified for 12-byte IVs and 16-byte tags.

2024-05-02 12:54 UTC, apetcher-amazon commented on SAW/proof/AES/evp-function-specs.saw
> +  crucible_precond {{ len < 2 ^^ 31 }};
Also, if the AWS-LC implementation allows lengths larger than this, then please add a caveat to the README file stating that the implementation is only verified for input lengths less than `2^^31` bytes.

2024-05-02 14:51 UTC, RyanGlScott commented on SPEC.md
> +| EVP_CipherInit_ex | <ul><li>The global variable `OPENSSL_ia32cap_P` exists and points to a value that [disables `AVX512[F|DQ|BW|VL]` instructions](https://www.openssl.org/docs/manmaster/man3/OPENSS
Ugh, GitHub's markdown parser for tables really doesn't like the fact that I used `|` characters in the phrase "`AVX512[F|DQ|BW|VL]`". I'll change this to something else (e.g., "`AVX512{F,DQ,BW,VL}`") in the hopes that that makes it format better.

2024-05-02 15:10 UTC, RyanGlScott commented on SAW/proof/AES/GHASH.saw
> +      goal_eval_unint ["pmult", "pmod", "gcm_polyval"];
I don't recall why this was set up this way, but I've confirmed that you only need to call `goal_eval_unint [...]` once. I'll remove the other calls, which are redundant.

2024-05-02 16:29 UTC, RyanGlScott commented on SAW/proof/AES/AES-GCM-check-entrypoint.go
> +		for j := 0; i < 2; i++ {
Good catch. Unfortunately, now that I've attempted a run with all four cases in parallel, I see that the SAW runners do indeed run out of memory. This suggests that we should stick to two cases in parallel. Do you have a preference for which two cases we'd want to prioritize?

2024-05-02 16:43 UTC, apetcher-amazon commented on SAW/proof/AES/helpers.saw
> +let llvm_verify_fixpoint_x86' m elf func globals pathsat loop_func_term spec tactic = if do_prove
Other proofs use `do_prove` to structure the proof and avoid proving the same fact multiple times. This comes up when there are dependencies between algorithms/proofs (e.g. HMAC depends on SHA-2). That isn't the case here, but I didn't consider the value of leaving it in for debugging convenience. I'm okay with leaving it as is.

2024-05-02 16:50 UTC, apetcher-amazon commented on SAW/proof/AES/AES-GCM-check-entrypoint.go
> +		for j := 0; i < 2; i++ {
Definitely leave in (0, 0), so we can claim that AES/GCM is verified when the input is whole blocks. If you can think of another case that might cause problems (e.g. because it uses more RAM or takes longer), then also check that one. Otherwise, any other case is fine.

2024-05-02 22:04 UTC, RyanGlScott commented on SAW/proof/AES/AESNI-GCM.saw
> +  crucible_precond {{ len < 2 ^^ 36 }};
This ultimately comes from [this line](https://github.com/GaloisInc/aws-lc/blob/98cac48f2fb9bdac41a83b8f2c9a263015cb87a6/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl#L109) of the x86-64 code in `aws-lc`, I believe, as this constraint is necessary to avoid integer overflow in the `add` instruction. I'll add a comment here to that effect.

2024-05-02 23:43 UTC, pennyannn commented on SAW/proof/AES/AESNI-GCM.saw
> +  crucible_precond {{ len < 2 ^^ 36 }};
That's interesting. Shouldn't this count as a memory safety issue? @apetcher-amazon, the C implementation doesn't check `len < 2 ^ 36`. So in theory, one can supply this function with a message exceeding that length and cause integer overflow. (One might argue that a message of that length might not appear in practice, though)

2024-05-03 00:11 UTC, RyanGlScott commented on SAW/proof/AES/evp-function-specs.saw
> + *   EVP_DecryptFinal_ex_spec expects an initial taglen value of AES_BLOCK_SIZE.
Yes, good catch. I've observed that I can change the uses of `0xffffffff` to `AES_BLOCK_SIZE` in the specifications for `EVP_{Encrypt,Decrypt}Update` and `EVP_EncryptFinal` and they will still succeed. That being said, `EVP_CipherInit_ex` still appears to `taglen` to `0xffffffff`...

2024-05-03 00:35 UTC, RyanGlScott commented on SAW/proof/AES/evp-function-specs.saw
> +  crucible_precond {{ ctx.len + (0 # len) < `TOTAL_MESSAGE_MAX_LENGTH }};
I believe this constraint ultimately arises from [this check in the code](https://github.com/GaloisInc/aws-lc/blob/98cac48f2fb9bdac41a83b8f2c9a263015cb87a6/crypto/fipsmodule/modes/gcm.c#L519-L523). (Note that `((UINT64_C(1) << 36) - 32)` is the same value as `TOTAL_MESSAGE_MAX_LENGTH`.) I'll note this in a comment.

2024-05-03 00:57 UTC, pennyannn commented on SAW/proof/AES/AESNI-GCM.saw
> +  crucible_precond {{ len < 2 ^^ 36 }};
Oh, I'm wrong. The C code does have such a [constraint](https://github.com/GaloisInc/aws-lc/blob/98cac48f2fb9bdac41a83b8f2c9a263015cb87a6/crypto/fipsmodule/modes/gcm.c#L519) as is shown in another comment from Ryan.

2024-05-03 04:09 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +aes_gcm_encrypt_update : AES_GCM_Ctx -> Array[64][8] -> [64] -> Array[64][8] -> (AES_GCM_Ctx, Array[64][8])
This definition is more closely related to the implementation than the NIST specification. How about saying something like the following:
```
// An unbounded specification for EVP_EncryptUpdate. This function performs an update to the `ctx` with input message `in` with length `len` and output the encrypted message as `out`.
```

2024-05-03 04:11 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +aes_gcm_decrypt_update ctx in len out =
Similarly for this function. I think it is more of a rewrite of the C implementation for `EVP_DecryptUpdate` than is related to the specification.

2024-05-03 04:16 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +aesni_gcm_encrypt :
Point out that this definition represent the bulk encrypt assembly. The bulk encryption phase processes 6 block chunks, and this definition also does 6 blocks in each recursive call.

2024-05-03 04:17 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +aesni_gcm_decrypt :
Similarly for this definition. Point out the bulk decryption.

2024-05-03 04:42 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +aesni_gcm_encrypt_impl_loop_step :
This function looks like part of the inductive invariant. Is that the case? Could you create a comment for it?

2024-05-03 04:43 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  ) = ( arrayRangeUpdate loop_out (loop_index * 96 + 192) (split (join [out_block0, out_block1, out_block2, out_block3, out_block4, out_block5]))
I couldn't figure out where the number `192` is coming from. Sorry I kept asking about these magical numbers. I wonder if you know in case.

2024-05-03 04:47 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
What does the number 24 refer to?

2024-05-03 04:56 UTC, pennyannn commented on SAW/proof/AES/goal-rewrites.saw
> +aesni_gcm_encrypt_impl_loop_hyp <- prove_theorem assume_unsat (rewrite (cryptol_ss ()) (unfold_term ["aesni_gcm_encrypt_impl_loop_stmt"] {{ aesni_gcm_encrypt_impl_loop_stmt }}));
This theorem is assumed and then used in the proof for `aesni_gcm_encrypt_impl_loop_thm`. I think this is probably some kind of a mocked induction proof. Is that correct? Could you add a comment to describe how it works? Also, I don't know if it should be mentioned in the caveats. @apetcher-amazon

2024-05-03 04:56 UTC, pennyannn commented on SAW/proof/AES/goal-rewrites.saw
> +aesni_gcm_decrypt_impl_loop_hyp <- prove_theorem assume_unsat aesni_gcm_decrypt_impl_loop_stmt;
Same here.

2024-05-03 04:56 UTC, pennyannn commented on SAW/proof/AES/goal-rewrites.saw
> +aesni_gcm_encrypt_Yi_hyp <- prove_theorem assume_unsat aesni_gcm_encrypt_Yi_stmt;
Also here.

2024-05-03 04:57 UTC, pennyannn commented on SAW/proof/AES/goal-rewrites.saw
> +aesni_gcm_decrypt_Yi_hyp <- prove_theorem assume_unsat aesni_gcm_decrypt_Yi_stmt;
Also here.

2024-05-03 04:57 UTC, pennyannn reviewed
I finished reviewing goal-rewrites and the Cryptol files.

2024-05-03 13:42 UTC, RyanGlScott commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  ) = ( arrayRangeUpdate loop_out (loop_index * 96 + 192) (split (join [out_block0, out_block1, out_block2, out_block3, out_block4, out_block5]))
I believe `192` comes from [this part](https://github.com/GaloisInc/aws-lc/blob/98cac48f2fb9bdac41a83b8f2c9a263015cb87a6/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl#L498-L504) of the x86-64 implementation of `aesni_gcm_encrypt` (thankfully, this part has an accompanying comment). I'll mention this here in the Cryptol comments.

2024-05-03 13:43 UTC, apetcher-amazon commented on SAW/proof/AES/AESNI-GCM.saw
> +  crucible_precond {{ len < 2 ^^ 36 }};
Also see page 8 of the [NIST spec](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf) that expresses a similar constraint on the length. In the spec, `len <= 2^36 - 32`, but checking for `len < 2^36` in this implementation accomplishes the same thing, since `len` is always a multiple of 144. Though it would be great if you could check my reasoning here, and add this information in the comment.

2024-05-03 14:04 UTC, apetcher-amazon commented on SAW/proof/AES/evp-function-specs.saw
> + *   EVP_DecryptFinal_ex_spec expects an initial taglen value of AES_BLOCK_SIZE.
I think we are better off using `0xffffffff` for `taglen` in all specs except for `EVP_DecryptUpdate`, but we are missing the formal verification of one function. During decryption, there should be a call like `EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, 16, tag)` before the call to `EVP_DecryptFinal` that sets the expected tag value and its length. This is when `0xffffffff` will be replaced with `AES_BLOCK_SIZE` in the context.

Can you also verify this function when called in this way? It should be trivial, since it just updates the context. While you are at it, we should probably also verify it when called to get the tag out of the context during encryption like `EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_GET_TAG, taglen, tag)`.

2024-05-03 14:10 UTC, apetcher-amazon commented on SAW/proof/AES/goal-rewrites.saw
> +aesni_gcm_encrypt_impl_loop_hyp <- prove_theorem assume_unsat (rewrite (cryptol_ss ()) (unfold_term ["aesni_gcm_encrypt_impl_loop_stmt"] {{ aesni_gcm_encrypt_impl_loop_stmt }}));
Yes, there should be a caveat associated with whatever is assumed here. If it is induction without a check to ensure that it is well-founded, then you can create a caveat similar to `SAWBreakpoint`.

2024-05-03 15:11 UTC, RyanGlScott commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
I'm afraid I'm not sure about this one.

2024-05-03 15:14 UTC, RyanGlScott commented on SAW/proof/AES/goal-rewrites.saw
> +aesni_gcm_encrypt_impl_loop_hyp <- prove_theorem assume_unsat (rewrite (cryptol_ss ()) (unfold_term ["aesni_gcm_encrypt_impl_loop_stmt"] {{ aesni_gcm_encrypt_impl_loop_stmt }}));
Yes, that is my understanding as well. I'll add a comment next to this use of `assume_unsat` (as well as similar uses elsewhere in this file) and add a caveat in `SPEC.md` to describe them.

2024-05-03 15:27 UTC, RyanGlScott commented on SAW/proof/AES/AESNI-GCM.saw
> +  crucible_precond {{ len < 2 ^^ 36 }};
You are correct—the proofs also go through with `len <= 2^^36 - 32` as the precondition. I will update this comment to mention why it suffices to check for `len < 2 ^^ 36` here (pointing to the NIST spec as well).

2024-05-03 17:24 UTC, RyanGlScott commented on SAW/proof/AES/evp-function-specs.saw
> + *   EVP_DecryptFinal_ex_spec expects an initial taglen value of AES_BLOCK_SIZE.
I've added two proofs of `EVP_CIPHER_CTX_ctrl` per your suggestions. I opted not to add `EVP_CIPHER_CTX_ctrl` to `SPEC.md`, as I wasn't sure if `EVP_CIPHER_CTX_ctrl` constituted a top-level AES-GCM function. I can add it if you'd like, however.

2024-05-03 18:36 UTC, apetcher-amazon commented on SAW/proof/AES/evp-function-specs.saw
> + *   EVP_DecryptFinal_ex_spec expects an initial taglen value of AES_BLOCK_SIZE.
Thanks! These are `EVP_` functions, so I think it is worthwhile to add them to SPEC.md.

2024-05-03 18:45 UTC, RyanGlScott commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
Ah, I think you are right on the money. Indeed, we need to account for the three iterations here, and given that this code is already multipying by 6, we are already taking the number of blocks into account. As for why this code uses an extra iteration, I'm not sure. I don't think there is a particularly good reason for doing so, however. We can just as well write this code without needing the extra iteration:

```diff
@@ -228,7 +228,7 @@ aesni_gcm_encrypt_impl_loop :
   LoopTuple ->
   LoopTuple
 aesni_gcm_encrypt_impl_loop len in out key ivec ctr Xi loop_tuple =
-  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
+  if get_loop_index loop_tuple + 3 < (len / 16) / 6
     then
       aesni_gcm_encrypt_impl_loop len in out key ivec ctr Xi
         (aesni_gcm_encrypt_impl_loop_step len in out key ivec ctr Xi loop_tuple)
```

And similarly for `aesni_gcm_decrypt_impl_loop`:

```diff
@@ -311,7 +311,7 @@ aesni_gcm_decrypt_impl_loop :
   LoopTuple ->
   LoopTuple
 aesni_gcm_decrypt_impl_loop len in out key ivec ctr Xi loop_tuple =
-  if 6 * (get_loop_index loop_tuple) + 12 <= len / 16
+  if get_loop_index loop_tuple + 1 < (len / 16) / 6
     then
       aesni_gcm_decrypt_impl_loop len in out key ivec ctr Xi
         (aesni_gcm_decrypt_impl_loop_step len in out key ivec ctr Xi loop_tuple)
```

The proofs continue to work after making this change. I like this much better, as we can more readily explain where the magic `3`/`1` numbers come from. I've went ahead and pushed these changes (along with comments)—let me know what you think.

2024-05-03 18:56 UTC, apetcher-amazon commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
I agree that the spec looks better now, but I don't understand how it is possible to prove these functions correct with both versions of the specs, since they seem to describe different behavior. Do you know the explanation for this?

2024-05-03 19:03 UTC, RyanGlScott commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
I think they are equivalent, actually. We can show this through equational reasoning:


```
   if 6 * (get_loop_index loop_tuple) + 24          <= len / 16
== if 6 * (get_loop_index loop_tuple) + 6 * (3 + 1) <= len / 16         [24 == 6 * (3 + 1)]
== if 6 * (get_loop_index loop_tuple + 3 + 1)       <= len / 16         [distributive law]
== if get_loop_index loop_tuple + 3 + 1             <= (len / 16) / 6   [divide by 6]
== if get_loop_index loop_tuple + 3                 <  (len / 16) / 6   [definition of <=]
```

This assumes that `get_loop_index loop_tuple <= len` and `len < 2 ^^ 36`, which are both things that hold true in this spot.

2024-05-03 20:45 UTC, apetcher-amazon commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
Oh. I didn't notice that you replaced `<=` with `<`. Now we are back to the original problem where I don't understand how this spec describes the behavior of the code. It looks to me like these functions in the implementation will process the input if it is exactly equal to the minimum size (96 bytes for decrypt and 288 bytes for encrypt). E.g. [here](https://github.com/GaloisInc/aws-lc/blob/98cac48f2fb9bdac41a83b8f2c9a263015cb87a6/crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl#L680) is the test for encrypt that will only return if the number of bytes is strictly less than 288. But the spec in both cases appears to need an extra 6 blocks. 

There is a good chance that I'm reading the Cryptol spec or assembly code incorrectly. Do you believe that the spec and implementation behave the same way when called on exactly the minimum size input?

2024-05-03 20:47 UTC, pennyannn commented on SAW/proof/AES/AESNI-GCM.saw
> +  // `len <= 2 ^^ 36 - 32`. Note that `len` is always a multiple of 144,
144 -> 96

2024-05-03 20:48 UTC, pennyannn approved these changes
LGTM. I just had one minor comment.

2024-05-03 21:57 UTC, pennyannn commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
I don't know if this is helpful in understanding the problem. 
The Cryptol specification for the bulk encryption is this function called `aesni_gcm_encrypt`. The definition in discussion here called `aesni_gcm_encrypt_impl_loop` is not the top-level definition but some function for helping with the invariant proof. (See: [link1](https://github.com/RyanGlScott/aws-lc-verification/blob/rgs/aes-gcm-unbounded-isolated/SAW/proof/AES/AESNI-GCM.saw#L41) and [link2](https://github.com/RyanGlScott/aws-lc-verification/blob/rgs/aes-gcm-unbounded-isolated/SAW/proof/AES/AESNI-GCM.saw#L85))

2024-05-03 22:01 UTC, RyanGlScott commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
Yes, I think this is the key point. `aesni_gcm_encrypt_impl_loop`'s key use is here:

https://github.com/awslabs/aws-lc-verification/blob/4397eb356e18b0f924a99d0e084bd50c2843c9db/SAW/proof/AES/goal-rewrites.saw#L453-L486

Note that we always call `aesni_gcm_encrypt_impl_loop_step` once after `aesni_gcm_encrypt_impl_loop` finishes, so this is likely a reason why the indexing in `aesni_gcm_encrypt_impl_loop` is "off-by-one" to account for it.

2024-05-06 14:33 UTC, apetcher-amazon commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
Thanks. This explanation helps. Can you add some form of this explanation as comments in the SAW script near these expressions (for both encrypt and decrypt)?

2024-05-06 15:49 UTC, RyanGlScott commented on SAW/spec/AES/AES-GCM-unbounded.cry
> +  if 6 * (get_loop_index loop_tuple) + 24 <= len / 16
I've added some comments about this.

2024-05-10 15:47 UTC, apetcher-amazon approved these changes

2024-05-10 15:48 UTC, merged