AES-KW(P) proofs
awslabs/aws-lc-verification pull request #24
Opened 2020-11-12 14:57 UTC by apetcher-amazon

Proof for AES Key Wrap, and Key Wrap with Padding. These operations are not available via the EVP API, so only the low-level functions are verified.

An moderately unpleasant aspect of this proof is that it depends on some definitions in the AES-GCM proof, as opposed to just AES. This is partially due to the organization of the AES specs in the cryptol-specs repository. When this change is merged, I can create tickets in this repo and in cryptol-specs describing the changes required to improve the organization. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-17 00:43 UTC, jldodds reviewed
Everything not commented on looks good to me. Comments are mostly aesthetic.

2020-11-17 00:43 UTC, jldodds commented on SAW/proof/AES_KW/AES_KW.saw
> +  // If the unwrap succeeds, the output buffer holds this symbolic value, and this value is equal to the result of unwrap.
This comment should not block merge

Leaving the failing result unspecified is a nice approach, since you definitely wouldn't want to prove code correct that looks at it.

@andreistefanescu I don't actually recall what it means if we don't have a pointsto in the postcondition but we do in the pre. If I recall correctly it's unallocated? Do we have this written down somewhere? If not I'll take the action to do that

My point is that if it's unallocated (as opposed to uninitialized), it *might* be nicer for this postcondition to point to fresh data, so that the memory could be reused if needed.

2020-11-17 00:43 UTC, jldodds commented on SAW/proof/AES_KW/AES_KW.saw
> +let AES_wrap_key_bad_length_spec withIv len = do {
It might be nice to comment the conditions under which this spec is expected to work

2020-11-17 00:43 UTC, jldodds commented on SAW/proof/AES_KW/AES_KW.saw
> +let AES_unwrap_key_bad_length_spec withIv len = do {
Same note about comments

2020-11-17 00:43 UTC, jldodds commented on SAW/proof/AES_KW/AES_KWP.saw
> +enable_experimental;
I know we're not doing this, so you can get us with the same comment later, but ideally we say what features we're using here, so we can more easily turn it off when they're no longer experimental.

2020-11-17 00:43 UTC, jldodds commented on SAW/proof/AES_KW/AES_KWP.saw
> +value_barrier_w_ov <- llvm_verify_x86 m "../../build/x86/crypto/crypto_test" "value_barrier_w"
Consider moving this to the bottom

2020-11-17 15:58 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +let {{ kw_iv = [0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6] : [8][8] }};
Changed to kw_default_iv, and similarly changed the IV in KWP to kwp_default_iv.

2020-11-17 16:05 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +let AES_wrap_key_bad_length_spec withIv len = do {
Added comments to describe all specs.

2020-11-17 16:05 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +let AES_unwrap_key_bad_length_spec withIv len = do {
Added comments to describe all specs.

2020-11-17 16:26 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +enable_experimental;
AES_KW.saw and AES_KWP.saw don't actually use experimental features, but some of the included files (AES.saw and helpers.saw) do. So I moved the enable_experimental to the files that need it, and I added a comment indicating which experimental feature is used (just crucible_llvm_verify_x86, I think, but please help me double check this).

2020-11-17 16:28 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +value_barrier_w_ov <- llvm_verify_x86 m "../../build/x86/crypto/crypto_test" "value_barrier_w"
Done.

2020-11-17 16:55 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +value_barrier_w_ov <- llvm_verify_x86 m "../../build/x86/crypto/crypto_test" "value_barrier_w"
Actually, I decided to move everything related to value_barrier_w to a separate file in the "common" directory. This way, the proof for value_barrier_w can be reused, and it also helps me contain the proofs that require x86 verification.

2020-11-17 17:06 UTC, jldodds commented on SAW/proof/AES_KW/AES_KW.saw
> +let {{ kw_iv = [0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6] : [8][8] }};
I didn't put the comment there, because it wasn't as obvious what that one should be called... it seems to get different names in different code/specs

2020-11-17 18:07 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +let {{ kw_iv = [0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6, 0xa6] : [8][8] }};
SP 800-38F uses the word "default" to describe these values, so I think it's reasonable to call them both defaults, even if the standard/implementation doesn't let you use any other value.

2020-11-17 18:36 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  // If the unwrap succeeds, the output buffer holds this symbolic value, and this value is equal to the result of unwrap.
I think the postcondition that I want is: out_ptr points to an allocated region of memory of length len, and if unwrap should succeed, then the value in memory is equal to the correct unwrapped value. I'm not completely sure of the semantics of crucible_conditional_points_to, but it looks like what I have is less precise (we don't know anything about out_ptr unless unwrap should succeed). So maybe I should replace it with a crucible_points_to?

2020-11-17 20:34 UTC, andreistefanescu requested changes
Looks good, I think we can simplify the specs a little

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KW.saw
> +  // The cryptol spec only produces the plaintext when unwrap succeeds. So this part is only checked conditionally.
Let's combine `AES_unwrap_key_spec` with `AES_unwrap_key_bad_length_spec`:

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KW.saw
> +  crucible_conditional_points_to {{(aesUnwrapKey (join (key_low#key_high)) iv indata).0}} out_ptr (crucible_term unwrapped);
Let's extract `(aesUnwrapKey ...)`, it appears four times and it's rather big:
```
let unwrap_res = {{ aesUnwrapKey (join (key_low#key_high)) iv indata }};
```

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out, out_ptr) <- ptr_to_fresh "out" (llvm_array (eval_size {|len+pad+8|}) (llvm_int 8));
same question about `out`

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out, out_ptr) <- ptr_to_fresh "out" (llvm_array (eval_size {|len + pad|}) (llvm_int 8));
same question about `out`

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  crucible_conditional_points_to {{(aesUnwrapKeyPadded (join (key_low#key_high)) kwp_default_iv indata).0}} out_ptr (crucible_term unwrapped);
Same as above, let's extract `(aesUnwrapKeyPadded ...)`

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  global_alloc_init "OPENSSL_ia32cap_P" {{ia32cap}};
Why not use `AES_wrap_key_padded_spec` directly:
```
let pad = eval_size {| (len+7)/8*8-len |};
```

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +let AES_wrap_key_padded_size_spec len pad = do {
Why not use `AES_wrap_key_padded_spec` directly:
```
let pad = eval_size {| (len+7)/8*8-len |};
```

2020-11-17 20:34 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +let AES_unwrap_key_padded_size_spec len pad = do {
same question as above

2020-11-17 21:12 UTC, jldodds commented on SAW/proof/AES_KW/AES_KW.saw
> +  // If the unwrap succeeds, the output buffer holds this symbolic value, and this value is equal to the result of unwrap.
We've discussed this more, and the behavior we see out of this line is in fact ideal.
A points to in the precondition with no matching points to in the post condition means that that memory remains allocated at the same size, but may no longer be initialized. As such it can be written to but not read, which is exactly the behavior we want from this function

2020-11-17 21:13 UTC, jldodds approved these changes

2020-11-17 22:49 UTC, apetcher-amazon commented on SAW/proof/AES/AES.saw
> +  low <- crucible_fresh_var "inv_key_low" (llvm_array (eval_size {|aes_key_len/2|}) (llvm_int 8));
Fixed.

2020-11-17 22:50 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  crucible_points_to out_ptr (crucible_term {{aesWrapKey (join key) iv indata}});
This is better. Thanks for the suggestion.

2020-11-17 22:50 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  (out, out_ptr) <- ptr_to_fresh "out" (llvm_array (eval_size {|len+8|}) (llvm_int 8));
Fixed.

2020-11-17 22:50 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  (out, out_ptr) <- ptr_to_fresh "out" (llvm_array len (llvm_int 8));
Fixed.

2020-11-17 22:50 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  // The cryptol spec only produces the plaintext when unwrap succeeds. So this part is only checked conditionally.
Done.

2020-11-17 22:51 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  crucible_conditional_points_to {{(aesUnwrapKey (join (key_low#key_high)) iv indata).0}} out_ptr (crucible_term unwrapped);
Done.

2020-11-17 22:51 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out, out_ptr) <- ptr_to_fresh "out" (llvm_array (eval_size {|len+pad+8|}) (llvm_int 8));
Fixed.

2020-11-17 22:51 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out, out_ptr) <- ptr_to_fresh "out" (llvm_array (eval_size {|len + pad|}) (llvm_int 8));
Fixed.

2020-11-17 22:51 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  crucible_conditional_points_to {{(aesUnwrapKeyPadded (join (key_low#key_high)) kwp_default_iv indata).0}} out_ptr (crucible_term unwrapped);
Done.

2020-11-17 22:52 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  global_alloc_init "OPENSSL_ia32cap_P" {{ia32cap}};
Fixed.

2020-11-17 22:52 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +let AES_wrap_key_padded_size_spec len pad = do {
Fixed.

2020-11-17 22:53 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +let AES_unwrap_key_padded_size_spec len pad = do {
Fixed.

2020-11-18 00:23 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KW.saw
> +  crucible_conditional_points_to {{(aesUnwrapKey (join (key_low#key_high)) iv indata).0}} out_ptr (crucible_term unwrapped);
I think this got lost

2020-11-18 00:30 UTC, andreistefanescu approved these changes
This looks great!

2020-11-18 00:30 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out_len, out_len_ptr) <- ptr_to_fresh "out" (llvm_int 64);
`ptr_to_fresh` -> `crucible_alloc`?

2020-11-18 00:30 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out_len_in, out_len_ptr) <- ptr_to_fresh "out" (llvm_int 64);
`ptr_to_fresh` -> `crucible_alloc`?

2020-11-18 00:30 UTC, andreistefanescu commented on SAW/proof/AES_KW/AES_KWP.saw
> +  out_len_out <- crucible_fresh_var "out_len_out" (llvm_int 64);
nit: `out_len_out` -> `out_len`

2020-11-18 14:26 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out_len, out_len_ptr) <- ptr_to_fresh "out" (llvm_int 64);
Fixed.

2020-11-18 14:26 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  (out_len_in, out_len_ptr) <- ptr_to_fresh "out" (llvm_int 64);
Fixed.

2020-11-18 14:27 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KWP.saw
> +  out_len_out <- crucible_fresh_var "out_len_out" (llvm_int 64);
Fixed.

2020-11-18 14:28 UTC, apetcher-amazon commented on SAW/proof/AES_KW/AES_KW.saw
> +  crucible_conditional_points_to {{(aesUnwrapKey (join (key_low#key_high)) iv indata).0}} out_ptr (crucible_term unwrapped);
Oops. Check the latest push. I think I got it this time.

2020-11-19 21:03 UTC, andrewhop approved these changes

2020-11-19 21:35 UTC, merged