Ecdh
awslabs/aws-lc-verification pull request #34
Opened 2020-12-20 06:27 UTC by andreistefanescu

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-20 06:32 UTC, andreistefanescu commented
@apetcher-amazon I plan to update the README after your first review

2020-12-21 18:29 UTC, apetcher-amazon reviewed
Additional general comments:

- Add verification for the other EVP functions needed for ECDH: EVP_PKEY_derive_init, EVP_PKEY_derive_set_peer
- Add verification for other functions needed to produce a new key pair. This should probably be shared between ECDH and ECDSA proofs. For example: https://wiki.openssl.org/index.php/Elliptic_Curve_Diffie_Hellman#Using_ECDH_in_OpenSSL
- Update README files.

2020-12-21 18:29 UTC, apetcher-amazon commented on SAW/proof/ECDH/ECDH.saw
> +let EVP_PKEY_derive_spec = do {
To be consistent with other proofs, should this go in a file called evp_function_specs.saw?

2021-01-19 14:25 UTC, apetcher-amazon requested changes
Looks good. I just have a couple of small documentation requests.

2021-01-19 14:25 UTC, apetcher-amazon commented on SAW/proof/ECDSA/ECDSA.saw
> +let max_sig_len = eval_size {| 1 + 1 + 1 + 1 + (ec_bits / 8 + 1) + 1 + 1 + (ec_bits / 8 + 1) |};
Looks like I missed this one in the ECDSA review. Can you explain the calculation here? Also, see if you can avoid duplication between sig_len and max_sig_len.

2021-01-19 19:59 UTC, apetcher-amazon approved these changes

2021-01-22 18:43 UTC, merged