Add proof for RSA-PSS.
awslabs/aws-lc-verification pull request #36
Opened 2021-02-03 08:58 UTC by andreistefanescu

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-03 21:25 UTC, apetcher-amazon requested changes
In addition to the detailed comments:

1) It looks like RSA key pair generation is not verified. Can you add a proof for this function? 
2) Please update the README files describing the proofs.
3) Need to add a line to the run_checks script to check the new RSA proof.

2021-02-03 21:25 UTC, apetcher-amazon commented on SAW/proof/common/internal.saw
> +// TODO: Override the functions that call into these CRYPTO_MUTEX functions,
Please make this change as part of the PR, or remove the TODO and open a ticket after the PR in merged.

2021-02-03 21:25 UTC, apetcher-amazon commented on SAW/proof/RSA/RSA.saw
> +  // TODO: Setting this to zero skips the blinding cache invalidation step for
Only need to check the default case. I.e. the value of this field when the context is created.

2021-02-15 11:54 UTC, andreistefanescu commented
@apetcher-amazon the RSA proof requires the latest SAW, I am working on updating SAW in the CI.

2021-02-15 20:50 UTC, apetcher-amazon requested changes
After reading through the code and README, I've come to the conclusion that this proof is a good start, but I don't think it is sufficiently "done" to include it in the top-level README files. I worry that someone will misunderstand what is verified, and will expect that the key generation function or RSA-PSS at higher than 1024 bits is verified. From our offline discussions, I get the impression that the best approach is to attempt a proof of RSA 3072 after some tool improvements.

Can you take the text about RSA out of the top-level README files and put it in a README file in the RSA directory? That README should clearly state that this is a work in progress.

2021-02-17 14:20 UTC, apetcher-amazon approved these changes

2021-02-17 14:20 UTC, merged